### ISSUE TITLE
bind to http

### ISSUE THREAD

**Issue by gromgsxr** [linuxserver/docker-kanzi#6]
by default it looks like it binds to port 8000 on https would it be possible to let it bind over http and let the reverse proxy handle the https-http stuff as this does not play well with my reverse proxy https-internal https

**Comment by gromgsxr** [comment]
i manually edited /etc/services.d/kanzi/run file in the container removing the --certfile & --keyfile parts and restarted the container and was greeted by [2022-04-05 00:03:45 +0000] [327] [INFO] Listening at: http://0.0.0.0:8000 (327)  and it now plays nice with my reverse proxy is this something that could be configurable without having to manually edit the file?

**Comment by aptalca** [comment]
Reverse proxies should have no problem with proxying https endpoints with self signed certs, so no plans to change the existing behavior
